### ISSUE TITLE
How to run "tex-match.macos"

### ISSUE THREAD

**Issue by perrogg** [zoeyfyi/TeX-Match#104]
I know I should use the detexify Mac app, but how to run "tex-match.macos" after downloading it on Mac OS?

**Comment by zoeyfyi** [comment]
It should just be a binary that you can run, i.e.

```
./tex-match.macos 
```

You many need to set the execution bit, i.e.

```
chmod +x tex-match.macos
```

**Comment by perrogg** [comment]
> It should just be a binary that you can run, i.e.
> 
> ```
> ./tex-match.macos 
> ```
> 
> You many need to set the execution bit, i.e.
> 
> ```
> chmod +x tex-match.macos
> ```

Thank you for your reply. I can run it now.
