### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by TheAlgorythm** [zoeyfyi/TeX-Match#40]
I dig through your code to know which font you are using. Even though I found and installed the 'Segoe UI' font, there are only rectangles.

**Comment by zoeyfyi** [comment]
Can you post a screenshot? Also what platform are you on?

**Comment by TheAlgorythm** [comment]
I would have uploaded a screenshot if Github won't give me the error " Something went really wrong, and we can’t process that file.". It works maybe later. My OS is Manjaro with an KDE desktop.

**Comment by zoeyfyi** [comment]
Hmm, thats strange I am on Manjaro/Gnome. I will try and setup a Manjaro/KDE VM, and see if I can replicate this.

**Comment by TheAlgorythm** [comment]
Well in the meanwhile i tried to start using the CLI.
There i got the following messages:
```sh
Gtk-Message: 12:13:10.313: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:13:10.376: Failed to load module "colorreload-gtk-module"
```
As i installed the system manually, there could be a missing package or something else.
```sh
pacman -Q | rg canberra
lib32-libcanberra 0.30+2+gc0620e4-3
lib32-libcanberra-gstreamer 0.30+2+gc0620e4-3
lib32-libcanberra-pulse 0.30+2+gc0620e4-3
libcanberra 0.30+2+gc0620e4-3
libcanberra-gstreamer 0.30+2+gc0620e4-3
libcanberra-pulse 0.30+2+gc0620e4-3
```

**Comment by zoeyfyi** [comment]
Are you using the snap, flatpak or binary? I just tested this on a fresh Manjaro/KVM VM and all of the releases work fine for me.

**Comment by TheAlgorythm** [comment]
Oh sorry, the Snap package

**Comment by zoeyfyi** [comment]
Ah, I remember this issue, I think its a problem with snap. This should solve it: https://askubuntu.com/questions/1224125/font-characters-displayed-as-squares-in-ubuntu-18-04

**Comment by TheAlgorythm** [comment]
That was the problem. Thank you for the great tool and support.
