### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [zoeyfyi/TeX-Match#42]
The current icon doesn't exactly follow the HIG, would you be interested in help with a new one?

Here's a an experiment:

![image](https://user-images.githubusercontent.com/1908896/97760063-a231f680-1b02-11eb-8f05-620658f4c64b.png)

**Comment by zoeyfyi** [comment]
That looks fantastic and it fits perfectly with the functionality of Tex Match! I will happily include it or you can send a PR

**Comment by bertob** [comment]
Cool, I'll add a symbolic and open a PR then :+1:
