### ISSUE TITLE
windows problem

### ISSUE THREAD

**Issue by henryzhu19** [zoeyfyi/TeX-Match#96]
the problem for windows： can not see the picture
(tex-match.exe:7632): Gtk-WARNING **: 12:37:28.212: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

**Comment by zoeyfyi** [comment]
Thanks for the report. I was planning to discontinue windows support #71, but seeing as there is some interest I will look into a native windows front end that should resolve problems like these that plagued the windows builds.

**Comment by zoeyfyi** [comment]
Fixed in #98
