### ISSUE TITLE
After building on Linux, how to run?

### ISSUE THREAD

**Issue by sierxue** [zoeyfyi/TeX-Match#97]
After building by cargo, how to run in Ubuntu 20.04? Thanks!

**Comment by zoeyfyi** [comment]
Should find the binary in the `target/debug` or `target/release` folder, for more information see [`cargo build` docs](https://doc.rust-lang.org/cargo/commands/cargo-build.html). Alternatively you can just use `cargo run` ([docs](https://doc.rust-lang.org/cargo/commands/cargo-run.html))
